# Generated by Django 2.2.6 on 2019-10-09 15:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Id', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('First_Name', models.CharField(max_length=10)),
                ('Last_Name', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Date_Of_Birth', models.DateField()),
                ('Company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=10)),
                ('Last_Name', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('Date_Of_Birth', models.DateField()),
                ('Mobile_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('City', models.CharField(max_length=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager')),
            ],
        ),
    ]
